#!/usr/bin/env python3
"""Build a compatible enriched view from the canonical Binance audit CSV.

The audit pipeline is the source of truth for official Binance fields and for
separately labelled estimates. This script only adds transparent convenience
columns; it never substitutes estimates for official Grid Profit, Total Profit,
their ratio, or Floating Profit.
"""
import os
import sys
import pandas as pd


def main(src, dst):
    df = pd.read_excel(src) if src.lower().endswith((".xlsx", ".xls")) else pd.read_csv(src)
    if df.empty:
        raise SystemExit(f"Input vide: {src}")

    # Be compatible with the canonical schema generated by src/audit_all.py.
    required = ["strategyId", "leverage"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise SystemExit(f"Colonnes indispensables absentes: {missing}; colonnes présentes: {list(df.columns)}")

    # Keep the source universe and values intact. The canonical scan already
    # applies leverage <= 1 and deduplicates IDs; don't silently alter its rows.
    if "runningTime" in df.columns:
        runtime = pd.to_numeric(df["runningTime"], errors="coerce")
        df["runningTime en J"] = runtime / 86400.0

    if "roi" in df.columns:
        df["roi (fourni par Binance)"] = pd.to_numeric(df["roi"], errors="coerce")
    elif "roi (fourni par Binance)" not in df.columns:
        df["roi (fourni par Binance)"] = pd.NA

    if {"pnl", "minInvestment"}.issubset(df.columns):
        pnl = pd.to_numeric(df["pnl"], errors="coerce")
        investment = pd.to_numeric(df["minInvestment"], errors="coerce")
        # A derived cross-check only; not a replacement for Binance ROI.
        df["roi (calculé)"] = (pnl / investment * 100).where(investment > 0)
    else:
        df["roi (calculé)"] = pd.NA

    if {"matchedTrades", "runningTime en J"}.issubset(df.columns):
        trades = pd.to_numeric(df["matchedTrades"], errors="coerce")
        days = pd.to_numeric(df["runningTime en J"], errors="coerce")
        df["Trades / J"] = (trades / days).where(days > 0)
    else:
        df["Trades / J"] = pd.NA

    # Crucially, do not derive official metrics from estimate columns here.
    # Keep gridProfit, totalProfit, ratio and floatingProfit exactly as sourced
    # by the audit pipeline, with their provenance/status columns untouched.
    if "score" in df.columns:
        df = df.sort_values("score", ascending=False, na_position="last", kind="stable")

    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
    df.to_csv(dst, index=False)
    print(f"{len(df)} lignes conservées -> {dst}")
    print("Grid Profit officiel renseigné :", int(df["gridProfit"].notna().sum()) if "gridProfit" in df else 0)
    print("Estimations séparées :", int(df["gridProfitEstimateMid"].notna().sum()) if "gridProfitEstimateMid" in df else 0)
    print("Aucun remplacement automatique des champs officiels par des estimations.")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else "results/current_multicriteria_enriched.csv")
